config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get 'pages/show'
  get 'search',  to: 'pages#search'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  resources :users, only: [:show]

  resources :explorers, only: [:index, :show] do
    resources :reservations, only: [:create]
  end
  resources :listings do
    resources :reservations, only: [:create]
    resources :reviews,      only: [:create, :destroy]
  end

  resources :reservations, only: [:index]
  get '/reserved',  to: 'host/reservations#reserved'
  get '/setdate',   to: 'reservations#setdate'
  get '/duplicate', to: 'reservations#duplicate'

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'manegelisting/:id/basics',      to: 'listings#basics',      as: 'manage_listing_basics'
  get 'manegelisting/:id/summary',     to: 'listings#summary',     as: 'manage_listing_summary'
  get 'manegelisting/:id/address',     to: 'listings#address',     as: 'manage_listing_address'
  get 'manegelisting/:id/price',       to: 'listings#price',       as: 'manage_listing_price'
  get 'manegelisting/:id/facility',    to: 'listings#facility',    as: 'manage_listing_facility'
  get 'manegelisting/:id/photos',      to: 'listings#photos',      as: 'manage_listing_photos'
  get 'manegelisting/:id/calendar',    to: 'listings#calendar',    as: 'manage_listing_calendar'
  get 'managelisting/:id/bankaccount', to: 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manegelisting/:id/map',         to: 'listings#map',         as: 'manage_listing_map'
  get 'manegelisting/:id/publish',     to: 'listings#publish',     as: 'manage_listing_publish'

  # stripe connect oauth path
  get '/connect/oauth',             to: 'stripe#oauth',       as: 'stripe_oauth'
  get '/connect/confirm',           to: 'stripe#confirm',     as: 'stripe_confirm'
  get '/connect/deauthorize',       to: 'stripe#deauthorize', as: 'stripe_deauthorize'


  namespace :host do
    resources :users, only: [:show]
  end
end

app/controllers/host/application_controller.rb
class Host::ApplicationController < ApplicationController
  layout 'host_application'
  before_action :authenticate_user!
end

app/controllers/host/reservations_controller.rb
class Host::ReservationsController < Host::ApplicationController
  def reserved
    @listings = current_user.listings
  end
end

app/controllers/host/users_controller.rb
class Host::UsersController < Host::ApplicationController  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/host/rooms_helper.rb
module Host::RoomsHelper
end

app/helpers/host/users_helper.rb
module Host::UsersHelper
end

app/views/shared/host/_container_path.html.erb
<div class="profile-edit-page-header">
  <h2>Add Listing</h2>
  <div class="breadcrumbs"><a href="#">Home</a><a href="#">Dasboard</a><span>Add Listing</span></div>
</div>

app/views/shared/host/_container_side_menu.html.erb
  <div class="fixed-bar fl-wrap" style="z-index: auto; position: relative; top: 0px;">
    <div class="user-profile-menu-wrap fl-wrap">
      <div class="user-profile-menu">
        <h3 class="title-m">Main</h3>
        <ul>
          <li>
            <%= link_to edit_host_user_path(:id), class: "text-m" do %>
              <i class="fa fa-user-o"></i> Edit profile
            <% end %>
          </li>
          <li>
            <a href="dashboard-messages.html" class="text-m">
              <i class="fa fa-envelope-o"></i> Messages <span>0</span>
            </a>
          </li>
          <li>
            <%= link_to edit_user_password_path(:id), class: "text-m" do%>
              <i class="fa fa-unlock-alt"></i>Change Password
            <% end %>
          </li>
        </ul>
      </div>

      <div class="user-profile-menu">
        <h3 class="title-m">Listings</h3>
        <ul>
          <li>
            <%= link_to host_rooms_path, class: "text-m" do %>
              <i class="fa fa-th-list"></i> My listigs
            <% end %>
          </li>
          <li>
            <%= link_to host_rooms_path, class: "text-m" do %>
              <i class="fa fa-calendar-check-o"></i> Bookings <span>2</span>
            <% end %>
          </li>
          <li>
            <a href="dashboard-review.html" class="text-m">
              <i class="fa fa-comments-o"></i> Reviews </a>
          </li>
          <li>
            <%= link_to new_host_room_path, class: "text-m user-profile-act" do %>
              <i class="fa fa-plus-square-o"></i> Add New
            <% end %>
          </li>
        </ul>
      </div>

      <% if user_signed_in? %>
        <%= link_to 'Log Out', destroy_user_session_path, class: "log-out-btn", method: :delete %>
      <% end %>
    </div>
  </div><div style="display: none; width: 260px; height: 487px; float: none;"></div>

app/views/shared/host/_header_nav.html.erb
<!-- nav-button-wrap-->
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<!-- nav-button-wrap end-->
<!--  navigation -->
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
      <%= link_to  class:"nav-link" do %>
        <i class="fa fa-fw fa-dashboard"></i>
        <span class="nav-link-text">Dashboard</span>
      <% end %>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Messages">
      <a class="nav-link" href="messages.html">
        <i class="fa fa-fw fa-envelope-open"></i>
        <span class="nav-link-text">Messages</span>
      </a>
    </li>
    <li class="nav-item">
      <%= link_to reserved_path, class: "nav-link" do %>
        <i class="fa fa-fw fa-calendar-check-o"></i>
        <span class="nav-link-text">Reserved<span class="badge badge-pill badge-primary">0 New</span></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to listings_path, class: "nav-link" do %>
        <i class="fa fa-fw fa-list"></i>
        <span class="nav-link-text">My Listings</span>
      <% end %>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Reviews">
      <a class="nav-link" href="reviews.html">
        <i class="fa fa-fw fa-star"></i>
        <span class="nav-link-text">Reviews</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Bookmarks">
      <a class="nav-link" href="bookmarks.html">
        <i class="fa fa-fw fa-heart"></i>
        <span class="nav-link-text">Bookmarks</span>
      </a>
    </li>
		<li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Add listing">
      <%= link_to new_listing_path, class: "nav-link" do %>
        <i class="fa fa-fw fa-plus-circle"></i>
        <span class="nav-link-text">Add Listing</span>
      <% end %>
    </li>
		<li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="My profile">
      <%= link_to host_user_path(current_user), class: "nav-link" do %>
        <i class="fa fa-fw fa-user"></i>
        <span class="nav-link-text">Profile</span>
      <% end %>
    </li>
  </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-envelope"></i>
          <span class="d-lg-none">Messages
            <span class="badge badge-pill badge-primary">12 New</span>
          </span>
          <span class="indicator text-primary d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">New Messages:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>David Miller</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>Jane Smith</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>John Doe</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all messages</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-bell"></i>
          <span class="d-lg-none">Alerts
            <span class="badge badge-pill badge-warning">6 New</span>
          </span>
          <span class="indicator text-warning d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">New Alerts:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-danger">
              <strong>
                <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all alerts</a>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        　<%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          <% end%>
        </li>
      <% end %>
    </ul>
  </div>
<!-- navigation  end -->