config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get 'pages/show'
  get 'search',  to: 'pages#search'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  resources :users, only: [:show]

  resources :explorers, only: [:index, :show] do
    resources :reservations, only: [:create]
  end
  resources :listings do
    resources :reservations, only: [:create]
    resources :reviews,      only: [:create, :destroy]
  end

  resources :reservations, only: [:index]
  get '/reserved',  to: 'host/reservations#reserved'
  get '/setdate',   to: 'reservations#setdate'
  get '/duplicate', to: 'reservations#duplicate'

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'manegelisting/:id/basics',      to: 'listings#basics',      as: 'manage_listing_basics'
  get 'manegelisting/:id/summary',     to: 'listings#summary',     as: 'manage_listing_summary'
  get 'manegelisting/:id/address',     to: 'listings#address',     as: 'manage_listing_address'
  get 'manegelisting/:id/price',       to: 'listings#price',       as: 'manage_listing_price'
  get 'manegelisting/:id/facility',    to: 'listings#facility',    as: 'manage_listing_facility'
  get 'manegelisting/:id/photos',      to: 'listings#photos',      as: 'manage_listing_photos'
  get 'manegelisting/:id/calendar',    to: 'listings#calendar',    as: 'manage_listing_calendar'
  get 'managelisting/:id/bankaccount', to: 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manegelisting/:id/map',         to: 'listings#map',         as: 'manage_listing_map'
  get 'manegelisting/:id/publish',     to: 'listings#publish',     as: 'manage_listing_publish'

  # stripe connect oauth path
  get '/connect/oauth',             to: 'stripe#oauth',       as: 'stripe_oauth'
  get '/connect/confirm',           to: 'stripe#confirm',     as: 'stripe_confirm'
  get '/connect/deauthorize',       to: 'stripe#deauthorize', as: 'stripe_deauthorize'


  namespace :host do
    resources :users, only: [:show]
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos,       dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews,      dependent: :destroy
  scope :actived, -> { where(active: true) }
  scope :near_location, -> (geolocation) { near(geolocation, 1, order: 'distance') }
  scope :order_desc_id, -> { order('id desc') }

  # validates :home_type, :listing_type, :accomodate, :bedroom, :bathroom, :listing_name, :summary, :address, presence: true
  validates :home_type, presence: true
  validates :listing_type, presence: true
  validates :listing_name, length: { maximum: 50 }
  validates :summary, length: { maximum: 250 }

  # geocode_by :address
  # after_validation :geocode, if: :address_changed?

  def average_star_rate
    if reviews.average(:rate).present?
      reviews.count == 0 ? 0 : reviews.average(:rate).round(1)
    else
      0
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  layout 'host_application'
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :basics, :summary, :address, :price,
                                     :photos, :calendar, :facility, :bankaccount, :publish, :map]
  before_action :access_deny, only: [:basics, :summary, :address, :price, :photos, :calendar, :facility, :publish, :map]

  # GET /listings or /listings.json
  def index
    @listings = current_user.listings
  end

  # GET /listings/:id or GET /listings/:id.json
  def show
    @photos = @listing.photos
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.build
  end

  # GET /listings/:id/edit
  def edit
  end

  # POST /listings or POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'リスティングを作成・保存をしました.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { redirect_to new_listing_path, notice: 'リスティングを作成・保存出来ませんでした' } # render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/:id or /listings/:id.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: '更新できました.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/:id or /listings/:id.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'リスティングを削除しました.' }
      format.json { head :no_content }
    end
  end

  def basics
  end

  def summary
  end

  def address
  end

  def price
  end

  def facility
  end

  def photos
    @photo = Photo.new
  end

  def calendar
  end

  def map
  end

  def publish
  end

  def bankaccount
    @user = @listing.user
    session[:listing_id] = @listing.id
  end

  def not_checked
    @listing = Listing.find(params[:listing_id])
    @listing.update(not_checked: params[:not_checked])
    render :nothing => true
  end

  private

  def access_deny
    if !(current_user == @listing.user)
      redirect_to root_path, notice: '他人の編集ページにはアクセスできません'
    end
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:home_type,
                                    :listing_type,
                                    :summary,
                                    :address,
                                    :is_tv,
                                    :is_kitchen,
                                    :is_air,
                                    :is_heating,
                                    :is_internet,
                                    :accomodate,
                                    :bedroom,
                                    :bathroom,
                                    :sheet,
                                    :price,
                                    :active,
                                    :user_id,
                                    :listing_name,
                                    :latitude,
                                    :longitude,
                                    :active)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/basics.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Dashboard</a>
  </li>
  <li class="breadcrumb-item active">edit listing-basic</li>
</ol>
<!-- /Breadcrumbs-->

<%= form_for @listing do |f| %>
  <section class="box_general u-pad_bottom_30">
    <div class="header_box version_2">
      <h2>Basic info edit</h2>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>Listing Title</label>
          <%= f.text_field :listing_name, placeholder: "Listing Title Name", class: "form-control", required: "true" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>Category</label>
          <div class="styled-select">
            <%= f.select :listing_type, [["宿泊","宿泊"], ["食事","食事"], ["体験","体験"], ["その他","その他"]], 
                        { prompt:"選択してください" }, { required: 'true', autofocus: 'true' } %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>Store Type</label>
          <div class="styled-select">
            <%= f.select :home_type, [["一軒家","一軒家"], ["店舗","店舗"], ["アパート","アパート"]],
                        { prompt:"選択してください" }, { required: 'true', autofocus: 'true' } %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <%= render 'shared/verticalnavbar'%>

  <p>
    <%= link_to "Back", listings_path, class: "btn btn-danger" %>
    <%= f.submit "Update", class: "button button--save u-border-rounded" %>
  </p>
<% end %>

app/views/listings/edit.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Dashboard</a>
  </li>
  <li class="breadcrumb-item active">Edit listing</li>
</ol>
<!-- /Breadcrumbs-->

<%= render 'form', listing: @listing %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Dashboard</a>
  </li>
  <li class="breadcrumb-item active">Listings list</li>
</ol>
<!-- /Breadcrumbs-->
<section class="box_general">
  <div class="header_box">
    <h2 class="d-inline-block">Listings list</h2>
    <div class="filter">
      <select name="orderby" class="selectbox" sb="24272890" style="display: none;">
        <option value="All">All</option>
        <option value="Public">Public</option>
        <option value="Pending">Pending</option>
      </select>
      <div id="sbHolder_24272890" class="sbHolder">
        <a id="sbToggle_24272890" href="#" class="sbToggle"></a>
        <a id="sbSelector_24272890" href="#" class="sbSelector">All</a>
        <ul id="sbOptions_24272890" class="sbOptions" style="display: none;">
          <li><a href="#All" rel="All" class="sbFocus">All</a></li>
          <li><a href="#Public" rel="Public">Public</a></li>
          <li><a href="#Pending" rel="Pending">Pending</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="list_general">
    <ul>
      <% @listings.each do |listing| %>
        <li>
          <article>
            <figure>
              <% if listing.photos.length > 0 %>
                <% if false %>
                <%= image_tag listing.photos[0].photo.url(:middle)  %>
                <% end %>
                <img src="http://placehold.jp/150x50.png" />
              <% else %>
                <img src="http://placehold.jp/150x50.png" />
              <% end %>
            </figure>
            <h4 class="listing-title"><%= listing.listing_name%></h4>
            <ul class="booking_list">
              <li><strong>写真: 登録済み</strong> <%= link_to "写真を登録する", manage_listing_photos_path(listing), data:{no_turbolink: true} %></li>
              <li><strong>設備: 登録済み</strong> <%= link_to "設備情報を登録する", manage_listing_facility_path(listing) %></li>
              <li><strong>料金: <%= listing.price %></strong> <%= link_to "料金を設定する", manage_listing_price_path(listing) %></li>
            </ul>
            <p><%= link_to "公開中", manage_listing_publish_path(listing), class: "btn_1 gray" %></p>
            <ul class="buttons">
              <li>
                <%= link_to "編集する", edit_listing_path(listing), class: "btn_1 gray approve" %>
              </li>
              <li>
                <%= link_to '削除する', listing, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "btn_1 gray delete" %>
              </li>
            </ul>
          </article>
        </li>
      <% end %>

      <li>
        <figure><img src="http://placehold.jp/150x50.png" alt=""></figure>
        <h4>Da Alfredo</h4>
        <ul class="booking_list">
          <li><strong>create date</strong> 11 November 2017</li>
          <li><strong>check details</strong></li>
          <li><strong>host</strong> Mark Twain</li>
        </ul>
        <p><a href="#0" class="btn_1 gray">公開中</a></p>
        <ul class="buttons">
          <li><a href="#0" class="btn_1 gray approve">編集する</a></li>
          <li><a href="#0" class="btn_1 gray delete">削除する</a></li>
        </ul>
      </li>
      <li>
        <figure><img src="http://placehold.jp/150x50.png" alt=""></figure>
        <h4>Pompidue Museum</h4>
        <ul class="booking_list">
          <li><strong>Booking date</strong> 11 November 2017</li>
          <li><strong>Booking details</strong> 2 People</li>
          <li><strong>Client</strong> Mark Twain</li>
        </ul>
        <p><a href="#0" class="btn_1 gray">未公開</a></p>
        <ul class="buttons">
          <li><a href="#0" class="btn_1 gray approve">編集する</a></li>
          <li><a href="#0" class="btn_1 gray delete">削除する</a></li>
        </ul>
      </li>
    </ul>
  </div>  
</section>
<!-- /box_general-->
	  
<nav aria-label="...">
  <ul class="pagination pagination-sm add_bottom_30">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>
<!-- /pagination-->
     
<% if false %>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Home type</th>
      <th>Room type</th>
      <th>Summary</th>
      <th>Address</th>
      <th>Is tv</th>
      <th>Is kitchen</th>
      <th>Is air</th>
      <th>Is heating</th>
      <th>Is internet</th>
      <th>Accomodate</th>
      <th>Bedroom</th>
      <th>Bathroom</th>
      <th>Sheet</th>
      <th>Price</th>
      <th>Active</th>
      <th>User</th>
      <th>Listing name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.home_type %></td>
        <td><%= listing.room_type %></td>
        <td><%= listing.summary %></td>
        <td><%= listing.address %></td>
        <td><%= listing.is_tv %></td>
        <td><%= listing.is_kitchen %></td>
        <td><%= listing.is_air %></td>
        <td><%= listing.is_heating %></td>
        <td><%= listing.is_internet %></td>
        <td><%= listing.accomodate %></td>
        <td><%= listing.bedroom %></td>
        <td><%= listing.bathroom %></td>
        <td><%= listing.sheet %></td>
        <td><%= listing.price %></td>
        <td><%= listing.active %></td>
        <td><%= listing.user_id %></td>
        <td><%= listing.listing_name %></td>
        <td><%= listing.latitude %></td>
        <td><%= listing.longitude %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_room_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <%= link_to 'New Room', new_room_path %>
<% end %>

app/views/listings/show.html.erb
<%= render 'shared/verticalnavbar'%>
<!-- ジャンボトロン -->
<div class="jumbotron row-space-0" style="margin-top: -20px; background: none;">

  <!-- カルーセル -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- リストの点 -->
    <% if @photos.length > 1 %>
        <ol class="carousel-indicators">
          <% @photos.each do |photo| %>
              <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
          <% end %>
        </ol>
    <% end %>

    <div class="carousel-inner" role="listbox">
      <% if @photos %>
          <% @photos.each do |photo| %>
              <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                <%= image_tag photo.photo.url(), style: "height:420px; width:100%; overflow:hidden;" %>
              </div>
          <% end %>
      <% end %>
    </div>

    <!-- 左右の矢印 -->
    <% if @photos.length > 1%>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    <% end %>
  </div>

</div>

<!-- サマリー -->
<div class="container-fluid container-listing-show">
  <div class="container">
    <div class="listing-summary row-space-3 row-space-top-3">
      <div class="row">

        </div>

        <!-- 予約フォーム -->
        <div class="col-md-3">
          <div class="panel panel-default panel-show">
            <div class="panel-heading">
              <span style="font-size:16px;"><%= @listing.price %>円（一晩あたり）</span>
            </div>

            <div class="panel-body panel-real">
              <%= form_for [@listing, @listing.reservations.new], url: new_listing_reservation_path(@listing), html: {method: "get"} do |f| %>

                  <!-- これは、予約をするときに、一緒におくる、データです。-->
                  <%= f.hidden_field :listing_id, value: @listing.id %>
                  <%= f.hidden_field :price_pernight, value: @listing.price %>
                  <% if false %>
                  <%= f.hidden_field :total_price, id:'reservation_total_price' %>
                  <% end %>
                  <div class="row row-space-2">
                    <div class="col-md-6">
                      <label>Check In</label>
                      <%= f.text_field :start_date, :class => 'form-control', placeholder: '開始' %>
                    </div>

                    <div class="col-md-6">
                      <label>Check Out</label>
                      <%= f.text_field :end_date, :class => 'form-control', placeholder: '終了',disabled:true %>
                    </div>
                  </div>


                  <div id="sitter-price" class="row row-space-2 hidden">
                    <div class="col-md-8 col-xs-8">

                    </div>
                    <div class="col-md-4 col-xs-4">

                    </div>
                  </div>

                  <!-- 手数料 -->
                  <div id="applicaton-fee" class="row row-space-2 hidden">
                    <div class="col-md-8 col-xs-8">

                    </div>
                    <div class="col-md-4 col-xs-4">

                    </div>
                  </div>

                  <!-- 合計料金 -->
                  <div id="total-price" class="row row-space-2 hidden">
                    <div class="col-md-8 col-xs-8">

                    </div>
                    <div class="col-md-4 col-xs-4">

                    </div>
                  </div>

                  <!-- エラーメッセージ -->
                  <div id="duplicate-message" class="row hidden">
                    <div class="col-md-12 text-center">
                      <label class="error">その日程は予約できません</label>
                    </div>
                  </div>

                  <div class="actions text-center">
                    <%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide",disabled:true %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- メインコンテント -->
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h3 class="row-space-3">このリスティングについて</h3>
      <p>テキスト</p>
    </div>

    <div class="col-md-3">

    </div>
  </div>


  <!-- レビュー     -->


  <!-- google map    -->
  <div class="row">
    <div class="col-md-9">
      <h3 class="row-space-3">アクセス</h3>
      <div id="map"></div>
    </div>

    <div class="col-md-3">

    </div>
  </div>
  <style>
    #map{
      width: 100%;
      height: 350px;
    }

  </style>



</div>

<script>
  $('#average_star_rate').raty({
    path: '/assets',
    readOnly: true,
    // score: star
  });
</script>

<script>
  function initMap() {

    // Create the map.
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: {lat: 10, lng: 10},
      mapTypeId: google.maps.MapTypeId.TERRAIN
    });


    // Add the circle for this city to the map.
    var cityCircle = new google.maps.Circle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map,
          center: {lat: 10, lng: 10},
      radius: 500
    });

  }

</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1BoiSo2jL950_AuFzV-f9ETgKn0uQl2I&signed_in=true&callback=initMap">
</script>

<script>
  $(function() {

    //日付について、それが選択不可能なものかを決める関数
    // inArray()について:dmyがdisabledDates配列になければ-1を返す
    function disable(date){
      dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
      return [$.inArray(dmy,disabledDates) == -1]; //trueを返す
    }

    // 不可能な日付の配列
    disabledDates = [];

    //事前にdatepickerに選択不可能な日付をセットするajax
    $.ajax({
      url: '/setdate',
      // this data is data for sending to url
      data: {'listing_id': <%= @listing.id %>},
      dataType: 'json',
      // callback argument: data is the response data
      // 下のurlを参考
      // http://stackoverflow.com/questions/4345045/javascript-loop-between-date-ranges

      // disabledDates[]にすでに予約されている日付を追加していく
      success: function(data){
        $.each(data,function(objID,objValue){
          for(var d = new Date(objValue.start_date); d <= new Date(objValue.end_date); d.setDate(d.getDate() + 1 )){
            disabledDates.push($.datepicker.formatDate('d-m-yy',d));
          }
        });

        // start_date欄がクリックされた時の処理
        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: disable,
          // 日付が選択された時の処理
          onSelect: function(selected){
            $('#reservation_end_date').datepicker("option","minDate",selected);
            $('#reservation_end_date').attr('disabled',false);

            var start_date = $(this).datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 +1 ;

            var inputs = {
              'start_date': start_date,
              'end_date': end_date,
              'listing_id':<%= @listing.id %>
            }

            // 選択日に重なりがないかチェックするajax
            $.ajax({
              url: "/duplicate",
              data: inputs,
              success: function(data){
                if (data.duplicate) {
                  // 重なりがある場合は、エラーメッセイジを表示
                  // また、合計料金,手数料を隠す
                  // 予約ボタンの押せないようにする
                  $('#duplicate-message').removeClass('hidden');
                  $('#sitter-price').addClass('hidden');
                  $('#applicaton-fee').addClass('hidden');
                  $('#total-price').addClass('hidden');
                  $('.btn-wide').attr('disabled', true);
                }else{
                  // 重なりがない場合は、エラーメッセージをかくす
                  // 合計料金をtotalに入れる
                  // total-priceを表示させる
                  $('#duplicate-message').addClass('hidden');

                  var sitter_price = days * <%= @listing.price %> ;
                  var applicaton_fee =  Math.round(sitter_price * 0.136) ;
                  var price_total = sitter_price + applicaton_fee;
                  $('#sitter-price').removeClass('hidden');
                  $('#total-price').removeClass('hidden');
                  $('#applicaton-fee').removeClass('hidden');
                  $('#sitter-price .col-md-8').text("シッター料:"+"<%= @listing.price %>"+"円"+" x "+days+"日");
                  $('#applicaton-fee .col-md-8').text("手数料:シッター料×13.6%");
                  $('#total-price .col-md-8').text("合計料金");

                  $('#sitter-price .col-md-4').text(sitter_price+"円");
                  $('#applicaton-fee .col-md-4').text(applicaton_fee+"円");
                  $('#total-price .col-md-4').text(price_total+"円");
                  $('#reservation_total_price').val(price_total);
                  $('.btn-wide').attr('disabled', false);
                }
              }
            });
          }
        });

        // end_date欄がクリックされた時の処理
        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: disable,
          onSelect: function(selected){
            $('#reservation_start_date').datepicker("option","maxDate",selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $(this).datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 +1 ;

            var inputs = {
              'start_date': start_date,
              'end_date': end_date,
              'listing_id':<%= @listing.id %>
            }

            // 選択日に重なりがないかチェックするajax
            $.ajax({
              url: "/duplicate",
              data: inputs,
              success: function(data){
                if (data.duplicate) {
                  // 重なりがある場合は、エラーメッセ-ジを表示
                  // 合計料金,手数料を隠す
                  // 予約ボタンの押せないようにする
                  $('#duplicate-message').removeClass('hidden');
                  $('#sitter-price').addClass('hidden');
                  $('#applicaton-fee').addClass('hidden');
                  $('#total-price').addClass('hidden');
                  $('.btn-wide').attr('disabled', true);
                }else{
                  // 重なりがなくokな場合は、エラーメッセージをかくす
                  // 合計料金をtotalに入れる
                  // total-priceを表示させる
                  $('#duplicate-message').addClass('hidden');

                  var sitter_price = days * <%= @listing.price %> ;
                  var applicaton_fee =  Math.round(sitter_price * 0.136) ;
                  var price_total = sitter_price + applicaton_fee;
                  $('#sitter-price').removeClass('hidden');
                  $('#total-price').removeClass('hidden');
                  $('#applicaton-fee').removeClass('hidden');
                  $('#sitter-price .col-md-8').text("シッター料:"+"<%= @listing.price %>"+"円"+" x "+days+"日");
                  $('#applicaton-fee .col-md-8').text("手数料:シッター料×13.6%");
                  $('#total-price .col-md-8').text("合計料金");

                  $('#sitter-price .col-md-4').text(sitter_price+"円");
                  $('#applicaton-fee .col-md-4').text(applicaton_fee+"円");
                  $('#total-price .col-md-4').text(price_total+"円");
                  $('#reservation_total_price').val(price_total);
                  $('.btn-wide').attr('disabled', false);
                }
              }
            });
          }
        });
      }
    });
  });
</script>





<p id="notice"><%= notice %></p>

<p>
  <strong>Home type:</strong>
  <%= @listing.home_type %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @listing.listing_type %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @listing.summary %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Is tv:</strong>
  <%= @listing.is_tv %>
</p>

<p>
  <strong>Is kitchen:</strong>
  <%= @listing.is_kitchen %>
</p>

<p>
  <strong>Is air:</strong>
  <%= @listing.is_air %>
</p>

<p>
  <strong>Is heating:</strong>
  <%= @listing.is_heating %>
</p>

<p>
  <strong>Is internet:</strong>
  <%= @listing.is_internet %>
</p>

<p>
  <strong>Accomodate:</strong>
  <%= @listing.accomodate %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @listing.bedroom %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @listing.bathroom %>
</p>

<p>
  <strong>Sheet:</strong>
  <%= @listing.sheet %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Active:</strong>
  <%= @listing.active %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<p>
  <strong>Listing name:</strong>
  <%= @listing.listing_name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @listing.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @listing.longitude %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>