config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get 'pages/show'
  get 'search',  to: 'pages#search'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  resources :users, only: [:show]

  resources :explorers, only: [:index, :show] do
    resources :reservations, only: [:create]
  end
  resources :listings do
    resources :reservations, only: [:create]
    resources :reviews,      only: [:create, :destroy]
  end

  resources :reservations, only: [:index]
  get '/reserved',  to: 'host/reservations#reserved'
  get '/setdate',   to: 'reservations#setdate'
  get '/duplicate', to: 'reservations#duplicate'

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'manegelisting/:id/basics',      to: 'listings#basics',      as: 'manage_listing_basics'
  get 'manegelisting/:id/summary',     to: 'listings#summary',     as: 'manage_listing_summary'
  get 'manegelisting/:id/address',     to: 'listings#address',     as: 'manage_listing_address'
  get 'manegelisting/:id/price',       to: 'listings#price',       as: 'manage_listing_price'
  get 'manegelisting/:id/facility',    to: 'listings#facility',    as: 'manage_listing_facility'
  get 'manegelisting/:id/photos',      to: 'listings#photos',      as: 'manage_listing_photos'
  get 'manegelisting/:id/calendar',    to: 'listings#calendar',    as: 'manage_listing_calendar'
  get 'managelisting/:id/bankaccount', to: 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manegelisting/:id/map',         to: 'listings#map',         as: 'manage_listing_map'
  get 'manegelisting/:id/publish',     to: 'listings#publish',     as: 'manage_listing_publish'

  # stripe connect oauth path
  get '/connect/oauth',             to: 'stripe#oauth',       as: 'stripe_oauth'
  get '/connect/confirm',           to: 'stripe#confirm',     as: 'stripe_confirm'
  get '/connect/deauthorize',       to: 'stripe#deauthorize', as: 'stripe_deauthorize'


  namespace :host do
    resources :users, only: [:show]
  end
end

app/views/shared/_banner.html.erb
<div class="container">
  <%= image_tag 'https://picsum.photos/1500/400/?random'%>
</div>

app/views/shared/_deviceErrorMsg.html.erb
<!-- deviseにエラーがある場合 -->
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<!--  footer -->
<footer class="footer" role="contentinfo">
  <div class="container u-pad_60_18">
    <div class="row">
      <div class="col-lg-5 col-md-12 p-r-5">
        <p class="footer__logo"><%= image_tag("logo.png", alt: "Logo", size: 48 ) %></p>
        <p class="footer__text">text texttexttexttexttext texttext texttexttexttext texttexttexttext texttexttexttext texttexttexttext</p>
        <div class="follow_us">
          <ul>
            <li>Follow us</li>
            <li><a href="#0"><i class="ti-facebook"></i></a></li>
            <li><a href="#0"><i class="ti-twitter-alt"></i></a></li>
            <li><a href="#0"><i class="ti-google"></i></a></li>
            <li><a href="#0"><i class="ti-pinterest"></i></a></li>
            <li><a href="#0"><i class="ti-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 ml-lg-auto">
        <h5>Useful links</h5>
        <ul class="links">
          <li><a href="about.html">About</a></li>
          <li><a href="login.html">Login</a></li>
          <li><a href="register.html">Register</a></li>
          <li><a href="blog.html">News &amp; Events</a></li>
          <li><a href="contacts.html">Contacts</a></li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6">
        <h5>Contact with Us</h5>
        <ul class="contacts">
          <li><a href="tel://0000000000"><i class="ti-mobile"></i> + 00 0000 0000</a></li>
          <li><a href="mailto:info@space.com"><i class="ti-email"></i> info@space.com</a></li>
        </ul>
        <div id="newsletter">
          <h6>News letter</h6>
          <div id="message-newsletter"></div>
            <form method="post" action="" name="form--newsletter" id="newsletter_form">
              <div class="form-group">
                <input type="email" name="email_newsletter" id="email_newsletter" class="form-control" placeholder="Your email">
                <input type="submit" value="Submit" id="submit-newsletter">
              </div>
            </form>
        </div>
      </div>
    </div>
    <!--/row-->
    <hr>
    <div class="row">
      <div class="col-lg-6">
        <ul id="footer-selector">
          <li><%= image_tag "dummy/card.png", height: 30 %></li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul id="additional_links">
          <li><a href="#">Terms and conditions</a></li>
          <li><a href="#">Privacy</a></li>
          <li><span>© 2018 space</span></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- /footer -->

app/views/shared/_head.html.erb
<title>Space</title>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>

app/views/shared/_header.html.erb
<!--  header -->
<header class="d-flex flex-column flex-md-row align-items-center px-md-4 bg-white u-box-shadow u-pad_8_8" role="banner">
  <%= link_to root_path, class: "navbar-brand mr-0 mr-md-2 mr-md-auto" do %>
    <%= image_tag("logo.png", alt: "Logo", size: 36 ) %>
  <% end %>

  <%= render partial: 'shared/header_user_menu' %>
</header>
<!-- /header -->

app/views/shared/_header_user_menu.html.erb
<nav class="my-2 my-md-0 mr-md-3">
  <ul class="navbar-nav bd-navbar-nav flex-row">
    <% if user_signed_in? %>
    <li><%= link_to "リスティング登録", new_listing_path, class: "p-2 text-dark" %></li>
    <% end %>
    <li><a href="#" class="p-2 text-dark">利用の流れ</a></li>
    <% if user_signed_in? %>
      <li>
        <%= link_to conversations_path, class: "p-2 text-dark" do %>
          <i class="fa fa-envelope"></i> メッセージ
        <% end %>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle p-2 text-dark" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <% if current_user.provider.present? %>
            <%= image_tag current_user.image, class:"img-circle profile-0" %>
            <%= current_user.name %>
          <% else %>
            <%= current_user.email.split("@")[0] %>
          <% end %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "プロフィール",  user_path(current_user) %></li>
          <li><%= link_to "リスティング管理",  listings_path %></li>
          <li><%= link_to "予約一覧",  reservations_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "アカウント作成", new_user_registration_path, class: "p-2 text-dark" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class: "p-2 text-dark" %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_main_banner.html.erb
<!-- Slider main container -->
<div class="swiper-container">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <div class="swiper-slide">
      <%= image_tag 'https://picsum.photos/1500/400/?random'%>
    </div>
    <div class="swiper-slide">
      <%= image_tag 'https://picsum.photos/1500/400/?random'%>
    </div>
    <div class="swiper-slide">
      <%= image_tag 'https://picsum.photos/1500/400/?random'%>
    </div>
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>

<script>
  var mySwiper = new Swiper ('.swiper-container', {
    loop: true,
    slidesPerView: 1,
    spaceBetween: 10,
    centeredSlides : true,
    pagination: '.swiper-pagination',
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    breakpoints: {
      767: {
        slidesPerView: 1,
        spaceBetween: 0
      }
    }
  })
</script>

app/views/shared/_verticalnavbar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?("listings") && action?("basics") %> listing-checked" id = "nav-basics">
          <%= link_to "基本事項", manage_listing_basics_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("summary") %>" id = "nav-description" >
          <%= link_to "リスティングの内容", manage_listing_summary_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("address") %>" id = "nav-address">
          <%= link_to "住所情報", manage_listing_address_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("facility") %>" id = "nav-address">
          <%= link_to "設備情報", manage_listing_facility_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("price") %>" id = "nav-price">
          <%= link_to "料金", manage_listing_price_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("photos") %>" id = "nav-photos">
          <%= link_to "写真", manage_listing_photos_path(@listing),data:{no_turbolink: true} %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("calendar") %>">
          <%= link_to "カレンダー", manage_listing_calendar_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("bankaccount") %>" id = "nav-bankaccount">
          <%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("publish") %>" id = "nav-publish">
          <%= link_to "公開する", manage_listing_publish_path(@listing) %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<% if false %>
<script>
  $(function(){

    // basicsが常に存在するので、値は5からスタート
    var notchecked = 5;

    // Modelに値が存在するならば、chekedクラスを追加して、not checked-- により、あたいをヘラす。
    <% if !@listing.listing_title.blank? && !@listing.listing_content.blank? %>
    $('#nav-description').attr('class', 'listing-checked');
    notchecked--;
    <%else%>
    $('#nav-description').attr('class', 'listing-notchecked');
    <% end %>

    <% if !@listing.address.blank? %>
    $('#nav-address').attr('class', 'listing-checked');
    notchecked--;
    <%else%>
    $('#nav-address').attr('class', 'listing-notchecked');
    <% end %>

    <% if !@listing.photos.blank? %>
    $('#nav-photos').attr('class', 'listing-checked');
    notchecked--;
    <%else%>
    $('#nav-photos').attr('class', 'listing-notchecked');
    <% end %>

    <% if !@listing.price_pernight.blank? %>
    $('#nav-price').attr('class', 'listing-checked');
    notchecked--;
    <%else%>
    $('#nav-price').attr('class', 'listing-notchecked');
    <% end %>

    <% if !@listing.user.stripe_user_id.blank? %>
    $('#nav-bankaccount').attr('class', 'listing-checked');
    notchecked--;
    <%else%>
    $('#nav-bankaccount').attr('class', 'listing-notchecked');
    <% end %>


    // notcheckedがあるなら、残り〜と表示して、違うなら、公開するを押せるようにする。
    if(notchecked > 0){
      $("li#nav-publish a").text("残り"+ notchecked +"ステップ");
      $("li#nav-publish a").removeAttr("href");
    }else{
      $("li#nav-publish a").text("公開する");
    }

    // ajaxでそのリスティングの、not_checkedランを更新する。
    $.ajax({
      // jsonで送った、notcheckedのデータでmodelのnot_checkedを更新する
      url: '/not_checked',
      // this data is data for sending to url
      data: {'listing_id': <%= @listing.id %>,'not_checked': notchecked},
      dataType: 'json'
    });
  });
</script>
<% end %>

app/views/shared/login.html.erb
<div id="logged-out">
    <h1>space-kit</h1>
    <h3>Sign in to access your space-kit</h3>
    <div id="firebaseui-auth-container"></div>
  </div>

  <div id="logged-in">
    <h1>Welcome, <span id="user"></span>!</h1>
    <h3>Enter a note and save it to your</h3>
  <div id="form">
    <form action="" method="post">
      <div class="form-group">
        <textarea id="note-content"></textarea>
      </div>
      <div class="form-group">
        <button id="add-note">Save note</button>
        <button id="sign-out">Sign out</button> 
      </div>
    </form>
  </div>

  <div id="notes-container"></div>